### ISSUE TITLE
Default type mapping for decimal types

### ISSUE THREAD

**Issue by nrvs** [cognitect/transit-python#14]
Perhaps this has already been an offline or internal discussion when working on this implementation, but while working with `transit-python` in a project I ran into something I thought was worth raising publicly.

Currently, in this implementation the transit type `big decimal` (transit tag `f`) maps to Python `float` on read and write, and only on read does transit type `decimal` (transit tag `d`) map to the `transit.transit_types.TaggedValue` class.

Based on reading the specification of [transit-format](https://github.com/cognitect/transit-format) and looking at other implementations (Java, Ruby, etc), I believe Python `float` should actually map to the transit type `decimal` (transit tag `d`) and Python `decimal.Decimal` should map to the transit type `big decimal` (transit tag `f`) instead.

**Comment by benkamphaus** [comment]
Hi @nrvs -- I agree with your assessment and have corrected the issue on master. Thanks for reporting!

**Comment by nrvs** [comment]
@benkamphaus awesome, glad I could help. Getting great use out of `transit`, cheers to you and the Cognitect crew.
