### ISSUE TITLE
Please provide a Python source distribution for this project on PyPI

### ISSUE THREAD

**Issue by jashugan** [cognitect/transit-python#15]
Pip understands two formats: wheel and source distributions [1]. You provide a wheel distribution and an egg (which is no longer recognized by pip). We have found wheels to be problematic on some platforms, can you please provide a source distribution on PyPI as well?

[1] https://docs.python.org/2/distutils/sourcedist.html

**Comment by jpaul6** [comment]
+1

**Comment by benkamphaus** [comment]
We'll include a source distribution with the next release. I'll update with a comment on this issue when it's available.

**Comment by benkamphaus** [comment]
The latest version (0.8.250) on PyPI now includes a source distribution as .zip and .tar.gz.
