### ISSUE TITLE
class_hash only iterates on direct ancestor classes while should iterate over mro

### ISSUE THREAD

**Issue by andreypopp** [cognitect/transit-python#18]
If you have a special representation for 
```
class A:
  pass
```
then it works for 
```
class B(A):
  pass
```
as well but not for
```
class C(B):
  pass
```

To fix this you need this line https://github.com/cognitect/transit-python/blob/master/transit/class_hash.py#L30 changed to 
```
for t in key.mro():
```

**Comment by benkamphaus** [comment]
Hi Andrey,

A fix for this is now on master. As opposed to your suggested change, we only try the mro lookup if `__bases__` fails to find a handler, as using `mro()` for all cases is a performance hit. The corresponding implication for performance for generic read/write handlers in transit-python is that a direct parent or e.g. a mixin pattern (anything that would succeed on a `__bases__` lookup) will be faster than inheriting past the child class level.

Best,
Ben

**Comment by andreypopp** [comment]
Thanks, Ben!
