### ISSUE TITLE
Handler's rep is executed twice during encoding

### ISSUE THREAD

**Issue by andreypopp** [cognitect/transit-python#19]
One execution happens during `marshal` and another during `emit_encoded`. I think it is possible to reuse representation between the two. Test case:
```
import transit.writer
import StringIO

class rep(object):

    @staticmethod
    def tag(v):
        return 'tag'

    @staticmethod
    def rep(v):
        print 'rep'
        return []

class A(object):
    pass

w = transit.writer.Writer(StringIO.StringIO(), 'json')
w.register(A, rep)
w.write({'a': A()})
```
outputs:
```
rep
rep
```

**Comment by benkamphaus** [comment]
Hi @andreypopp - thanks for the report. I've modified the conditional rep call in marshal on master so that it only gets called conditionally if needed.

**Comment by andreypopp** [comment]
Thank you
