### ISSUE TITLE
Support for python3?

### ISSUE THREAD

**Issue by jakemcc** [cognitect/transit-python#22]
Any plans for supporting python3?

**Comment by benkamphaus** [comment]
Hi @jakemcc -- it's something we've considered and is in the backlog at present. Give enough user interest, it's something we'd look at bumping in priority.

Anyone browsing - feel free to note your interest here as well.

**Comment by snoe** [comment]
Here's someone else mentioning the lack of python3 support. https://news.ycombinator.com/item?id=10385392

**Comment by benkamphaus** [comment]
Hi @snoe -- while it's correct that we don't support python3 at present, the linked post is incorrect as transit-python is compatible with PyPy.

**Comment by Adamanthil** [comment]
We are definitely interested in Python3 support as well. In particular, we are exploring building a GraphQL layer on top of Django.

**Comment by humphrej** [comment]
+1 for python 3 support

**Comment by freckletonj** [comment]
what would a road map for python 3 support look like (as guidance for ppl who want to contribute?)

**Comment by ohpauleez** [comment]
Hi all -- we're actively working on Python3 support.  We have just one small piece left to address.  Once we resolve it, we'll post back to this issue.  Thanks!

**Comment by ohpauleez** [comment]
Python 3 support is now on master.  We'll make a release soon.

Thanks all for your encouragement, enthusiasm, support, and patience.

**Comment by stumitchell** [comment]
Hmm @ohpauleez I'm waiting on this release
