### ISSUE TITLE
With 'json_verbose', the Writer does caching for dict keys

### ISSUE THREAD

**Issue by mrcslws** [cognitect/transit-python#23]
~~~python
from transit.writer import Writer
from StringIO import StringIO
io = StringIO()
writer = Writer(io, "json_verbose")
writer.write([
    {'myKey1': 42},
    {'myKey1': 42},
])
print str(io.getvalue())
~~~

Expected output:  **(I confirmed this is what Clojure does)**

~~~
[{"myKey1":42},{"myKey1":42}]
~~~

Actual output:

~~~
[{"myKey1":42},{"^0":42}]
~~~

It's in a weird partly-caching mode.

My ClojureScript expects `:json-verbose`, so this is causing bad decode issues. And I can't switch to `:json` because of https://github.com/cognitect/transit-cljs/issues/22. Hopefully I'm looking at this right?

**Comment by benkamphaus** [comment]
Verified. I'll investigate a fix. Thanks for the report!

**Comment by benkamphaus** [comment]
@mrcslws Thanks again for the report. We've fixed this bug on the latest version of master. We'll include it in a release soon.
