### ISSUE TITLE
Equality for keyword transit type is mysterious

### ISSUE THREAD

**Issue by memoia** [cognitect/transit-python#25]
Using transit-python==0.8.250,

I'm not sure if this is intentional, but look what happens when I compare two Keyword instances that have the same string:

```python
>>> from transit.transit_types import Keyword as K
>>> assert K('keyword') == K('keyword')
>>> assert K('keyword') != K('keyword')
```

One of these should raise an `AssertionError`, no?

**Comment by sviterok** [comment]
+1 It seems like it's fixed in current "master"

**Comment by benkamphaus** [comment]
Hi @memoia and @sviterok -- that's correct, this issue has been resolved on the current master branch. I'll be pushing a release out soon.

**Comment by benkamphaus** [comment]
Release [0.8.282](https://groups.google.com/d/msg/transit-format/AJwXyroqP_8/YsPflrkLGwAJ) includes a fix for this.
