### ISSUE TITLE
Can't import Reader or Writer 

### ISSUE THREAD

**Issue by abhi18av** [cognitect/transit-python#29]
Hi transit-python team)

I've run into errors during simple import operation. I read in the issues that it's recently ported to python3 so, I've copied here my specific config.

```python
❯ python3
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from transit.writer import Writer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eklavya/anaconda/lib/python3.5/site-packages/transit/writer.py", line 17, in <module>
    from constants import SUB, ESC, RES, MAP_AS_ARR, QUOTE
ImportError: No module named 'constants'
>>> from transit.reader import Reader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eklavya/anaconda/lib/python3.5/site-packages/transit/reader.py", line 16, in <module>
    import sosjson
ImportError: No module named 'sosjson'
>>>
```

**Comment by inirudebwoy** [comment]
Hi,
Seems that you didn't install the package and try to run it from the folder.
I'd advise you to create a virtual environment,run `python setup.py install` and then try to import.

**Comment by abhi18av** [comment]
Oh, that did solve the problem! But, to me, it's a bit counter-intuitive since I used the generic `pip install transit-python` which has always served my needs well enough.

Actually, I did want to install it as a global package so I wanted to use `pip`

**Comment by inirudebwoy** [comment]
Yes, indeed. After installing with pip it does complain about missing imports.
Looks like the package in PyPI has not been updated as it's imports are different than in this repository.

If you want to install it globally just run `python setup.py install` as root.

**Comment by abhi18av** [comment]
Oh, right. All done then)

Thank you for your time @inirudebwoy :+1:
