### ISSUE TITLE
How to serialize frozendicts

### ISSUE THREAD

**Issue by raunakb94** [cognitect/transit-python#30]
I have been trying to decode transit objects using the json reader factory. 
The return type of which is frozendict.
Is there a way to convert these objects into valid python dictionaries.

**Comment by inirudebwoy** [comment]
Hi,

`frozendict` class inherits from `Mapping` and `Hashable` abstract classes. In effect it has partial interface of regular python dictionary object. 
Knowing that you may easily convert `frozentdict` by initialising new dictionary with `dict` keyword and passing existing `frozendict`.

Here you have example:
```
In [26]: from transit.transit_types import frozendict

In [27]: f = frozendict({'a': 1})

In [28]: f
Out[28]: frozendict({'a': 1})

In [29]: d = dict(f)

In [30]: d
Out[30]: {'a': 1}

In [31]: type(d)
Out[31]: dict
```

I hope this answers your question.

**Comment by ohpauleez** [comment]
Thanks @inirudebwoy!

**Comment by nblumoe** [comment]
Is there a way to serialise the full data structure easily when it includes nested, frozen data? Would I have to walk the data structure myself and convert everything?

Some kind of `unfreeze` method would be awesome.
