### ISSUE TITLE
TypeError when using None as a key

### ISSUE THREAD

**Issue by p-himik** [cognitect/transit-python#31]
Executing
```python
from transit.writer import Writer
from io import StringIO
buffer = StringIO()
writer = Writer(buffer)
writer.write({None: 1})
```
results in
```
TypeError: Can't convert 'NoneType' object to str implicitly
```

The issue is in `transit.writer.Marshaler#emit_string` that assumes that its `string` argument is not None.

**Comment by p-himik** [comment]
Or in `transit.writer.Marshaler#emit_nil` that should supply an empty string instead of None.

**Comment by benkamphaus** [comment]
Now resolved on latest master, will be included in a release soon.
