### ISSUE TITLE
Marshalling of int-like objects not inherited from int is broken

### ISSUE THREAD

**Issue by p-himik** [cognitect/transit-python#32]
Consider `numpy.int64`. If we simply add it via `Writer.register(numpy.int64, IntHandler)`, it won't work since  `Marshaller.emit_int` explicitly checks `isinstance(rep, int)` and if the check returns False, `rep` is passed as-is, without calling `str`.

**Comment by benkamphaus** [comment]
Now resolved on latest master, will be included in a release soon.
