### ISSUE TITLE
Python 3.8: collections.abc is deprecated

### ISSUE THREAD

**Issue by Azd325** [cognitect/transit-python#34]
It seems transit will stop to work with the release of Python 3.8.
 
```
transit/transit_types.py:15: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
transit/class_hash.py:19: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```

**Comment by pangloss** [comment]
Python 3.8 is out. Is this library (or transit in general) still being maintained (no response would indicate that it is not)?

**Comment by benkamphaus** [comment]
Now resolved on latest master, will be included in a release soon.

**Comment by Azd325** [comment]
> Now resolved on latest master, will be included in a release soon.

Any news for the release? :)
